export const auditLogs = [
  {
    id: 1,
    timestamp: "2026-07-18 09:14:23",
    application: "SecurePay",
    user: "john.doe@securepay.com",
    ip: "192.168.1.15",
    device: "Windows 11 • Chrome",
    location: "Bengaluru, India",
    risk: 18,
    decision: "Access Granted",
    policy: "High Security",
    method: "Password + Face ID",
    status: "Success",
  },
  {
    id: 2,
    timestamp: "2026-07-18 09:21:41",
    application: "HR Portal",
    user: "alice@company.com",
    ip: "172.16.20.5",
    device: "MacBook Pro • Safari",
    location: "Hyderabad, India",
    risk: 47,
    decision: "MFA Required",
    policy: "Adaptive MFA",
    method: "Password + OTP",
    status: "Warning",
  },
  {
    id: 3,
    timestamp: "2026-07-18 09:34:12",
    application: "CRM",
    user: "bob@crm.com",
    ip: "203.14.88.10",
    device: "Android • Chrome",
    location: "Mumbai, India",
    risk: 81,
    decision: "Access Denied",
    policy: "Zero Trust",
    method: "Blocked",
    status: "Critical",
  },
  {
    id: 4,
    timestamp: "2026-07-18 09:48:53",
    application: "Finance Portal",
    user: "finance.admin@corp.com",
    ip: "10.1.14.2",
    device: "Windows 11 • Edge",
    location: "Chennai, India",
    risk: 22,
    decision: "Access Granted",
    policy: "Finance Policy",
    method: "Password + FIDO2",
    status: "Success",
  },
  {
    id: 5,
    timestamp: "2026-07-18 10:02:18",
    application: "Developer Console",
    user: "hemanth@secureauth.ai",
    ip: "192.168.100.18",
    device: "Ubuntu • Firefox",
    location: "Vijayawada, India",
    risk: 63,
    decision: "MFA Required",
    policy: "Developer Policy",
    method: "Password + Authenticator",
    status: "Warning",
  },
  {
    id: 6,
    timestamp: "2026-07-18 10:19:44",
    application: "Customer Portal",
    user: "customer@securepay.com",
    ip: "185.21.17.99",
    device: "iPhone • Safari",
    location: "Delhi, India",
    risk: 12,
    decision: "Access Granted",
    policy: "Standard",
    method: "Password",
    status: "Success",
  },
];