export const applications = [
  {
    id: 1,
    name: "SecurePay",
    type: "Web",
    policy: "High Security",
    users: 1423,
    status: "Active",
    clientId: "sa_live_x82A9KLM",
    clientSecret: "••••••••••••••••",
    redirectUri: "https://securepay.com/auth/callback",
  },
  {
    id: 2,
    name: "HR Portal",
    type: "Internal",
    policy: "MFA Required",
    users: 438,
    status: "Active",
    clientId: "sa_live_J82KKL29",
    clientSecret: "••••••••••••••••",
    redirectUri: "https://hr.company.com/login",
  },
  {
    id: 3,
    name: "CRM",
    type: "SaaS",
    policy: "Medium Security",
    users: 912,
    status: "Active",
    clientId: "sa_live_MNB92PQL",
    clientSecret: "••••••••••••••••",
    redirectUri: "https://crm.company.com/auth",
  },
];