export const users = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@securepay.com",
    role: "Administrator",
    application: "SecurePay",
    status: "Active",
    mfa: true,
    lastLogin: "18 Jul 2026 • 09:14 AM",
    location: "Bengaluru, India",
    device: "Windows 11 • Chrome",
  },
  {
    id: 2,
    name: "Alice Johnson",
    email: "alice@company.com",
    role: "Manager",
    application: "HR Portal",
    status: "Active",
    mfa: true,
    lastLogin: "18 Jul 2026 • 08:32 AM",
    location: "Hyderabad, India",
    device: "MacBook Pro • Safari",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bob@crm.com",
    role: "Employee",
    application: "CRM",
    status: "Locked",
    mfa: false,
    lastLogin: "17 Jul 2026 • 10:45 PM",
    location: "Mumbai, India",
    device: "Android • Chrome",
  },
  {
    id: 4,
    name: "Sarah Wilson",
    email: "sarah@finance.com",
    role: "Finance Admin",
    application: "Finance Portal",
    status: "Active",
    mfa: true,
    lastLogin: "18 Jul 2026 • 07:58 AM",
    location: "Chennai, India",
    device: "Windows 11 • Edge",
  },
  {
    id: 5,
    name: "Hemanth B",
    email: "hemanth@secureauth.ai",
    role: "Super Admin",
    application: "Developer Console",
    status: "Active",
    mfa: true,
    lastLogin: "18 Jul 2026 • 11:05 AM",
    location: "Vijayawada, India",
    device: "Ubuntu • Firefox",
  },
  {
    id: 6,
    name: "Emma Davis",
    email: "emma@customer.com",
    role: "Customer",
    application: "Customer Portal",
    status: "Inactive",
    mfa: false,
    lastLogin: "15 Jul 2026 • 05:20 PM",
    location: "Delhi, India",
    device: "iPhone • Safari",
  },
];